In [21]:
import numpy as np
arr = np.array([[.2,.3],
               [-1.1,2],
               [1,-2.2],
               [.5,-1],
               [-.6,1]])

row_means = np.mean(arr, axis=0)
row_means

array([-2.22044605e-17,  2.00000000e-02])

In [24]:
#Centered means
arr2 = arr - row_means
arr2

array([[ 0.2 ,  0.28],
       [-1.1 ,  1.98],
       [ 1.  , -2.22],
       [ 0.5 , -1.02],
       [-0.6 ,  0.98]])

In [25]:
cov_matrix = np.cov(arr2, rowvar=False)  # Set rowvar to False to treat columns as variables

print("Covariance Matrix:")
print(cov_matrix)

Covariance Matrix:
[[ 0.715 -1.36 ]
 [-1.36   2.732]]


In [26]:
import pandas as pd
cov_matrix = np.array([[0.715, -1.112],
                      [-1.112, 2.72]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Eigenvalues will be stored in eigenvalues
# Eigenvectors will be stored in eigenvectors
eigen_df = pd.DataFrame({'Eigenvalue': eigenvalues, 'Eigenvector': list(eigenvectors)})

# Print the DataFrame
print(eigen_df)

   Eigenvalue                                  Eigenvector
0    0.220319   [-0.9136716651617358, 0.40645305790531433]
1    3.214681  [-0.40645305790531433, -0.9136716651617358]


In [27]:
eigenvector = eigenvectors[1]
eigenvector.reshape(-1,1)

transformed_data = np.dot(arr2, eigenvector)
transformed_data

array([-0.33711868, -1.36197153,  1.62189804,  0.72871857, -0.6515264 ])